global:
  shell_cmd: bash -c

init: |
  echo "initialization commands"

e2e_tests: |
  ${build all}
  ${push all}
  ${init}
  ./e2e pnpm test
  ${purge}

services:
  frontend:
    start:
    build: |
      docker build . -t streampai.frontend:latest
    push: |
      docker push streampai.frontend:latest
    dev:
    test:
      depends_on:
      - backend/main
      - backend/stream_chat

  backend/main:
  backend/stream_chat:

purge: |
  echo "project cleanup commands
  for example:
  - docker compose down
  or
  - kubectl delete -f k3s/"

