global:
  shell_cmd: nu -c
include:
  - ./config/
  # - ./commands_optimus.yml

start: 
  description: |
    Start the application
  run: |
    echo "sup"
    docker compose -f compose.yml -f compose.dev.yml up -d  
  

# script that runs e2e tests
e2e_tests: 
  shell: nu -c
  run: |
    echo "test"
    echo "multiline"
  # file: ./e2e_tests.nu

services:
  frontend:
    root: ./config
    dev:
      shell: nu -c
      run: |
        ls
    build: |
      ls

lscmd:
  root: ./config
  run: |
    ls